networks:
  av2_net:
    driver: bridge

volumes:
  grafana-storage:

services:
  api:
    container_name: av2
    image: vktgabriel/av2:latest
    depends_on:
      - keycloak
    ports:
      - "9000:9000"
    networks:
      - av2_net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - av2_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - av2_net
    volumes:
      - grafana-storage:/var/lib/grafana

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    networks:
      - av2_net
    ports:
      - "8080:8080"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    command: ['start-dev', "--import-realm"]